### ISSUE TITLE
bengtssondd.it

### ISSUE THREAD

**Issue by solidus1983** [larssb/HushDNS#2]
Seems the website blog is down bud so can not read up on your setup.

**Comment by larssb** [comment]
Soon to be up again. Hopefully already tomorrow. Sorry for the annoyance.

--
Mvh. / Kind regards
Lars Bengtsson

- Health is wealth, movement is medicine -

**Comment by solidus1983** [comment]
> Soon to be up again. Hopefully already tomorrow. Sorry for the annoyance.
> […](#)
> -- Mvh. / Kind regards Lars Bengtsson - Health is wealth, movement is medicine -
> On 24 Jan 2021, at 17.31, solidus1983 ***@***.***> wrote: ﻿ Seems the website blog is down bud so can not read up on your setup. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

No worries bud, just thought i'd give you heads up on it.

**Comment by larssb** [comment]
Hi @solidus1983,

The website is live again and has been for several days. Just to let you know.

Have a great 1

**Comment by solidus1983** [comment]
I can see it, nice one. Will give it a good read.

**Comment by larssb** [comment]
Sounds great. Enjoy.

--
Mvh. / Kind regards
Lars Bengtsson

- Health is wealth, movement is medicine -
