### ISSUE TITLE
Pi-hole error because Pi-hole isn't running on port 80

### ISSUE THREAD

**Issue by nyvanga** [larssb/HushDNS#5]
So I got this error when trying to access the web interface on http://localhost:808 (since `WEB_PORT: "808"` set [here](https://github.com/larssb/HushDNS/blob/3b88e76263e50a5b8e4b004401f3c0445db6f529/unit-deployment/pi-hole/docker-compose.yml#L18))
```
[ERROR]: Unable to parse results from queryads.php: Unhandled error message ()
```
The issues seems to be that some PHP, in [v4.4](https://github.com/larssb/HushDNS/blob/3b88e76263e50a5b8e4b004401f3c0445db6f529/unit-deployment/pi-hole/docker-compose.yml#L20) of Pi-hole, expects the server to be on port 80 ([Pi-hole issue](https://github.com/pi-hole/pi-hole/issues/2195)). It has been fixed in some later version, so an easy fix is to run latest.

**Comment by larssb** [comment]
There you go @nyvanga - I hope it helps.
